version: "3"

services:
  vscode:
    build: .
    image: latexdevcontainer
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=
    entrypoint: zsh -c "while sleep 1000; do :; done"
