name: Buildx release
on:
  release:
    types: [published]
    paths:
      - .github/workflows/buildx-release.yml
      - shell/**
      - .dockerignore
      - Dockerfile
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=${GITHUB_REF##*/} \
            -t qmcgaw/latexdevcontainer:${GITHUB_REF##*/} \
            --push \
            .
