name: Buildx latest
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/buildx-latest.yml
      - shell/**
      - .dockerignore
      - Dockerfile
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=alpine \
            -t qmcgaw/latexdevcontainer \
            --push \
            .
      - run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/latexdevcontainer/xq5q57-42Lbxy5YlOvMG2gNnUD0= || exit 0
